### ISSUE TITLE
Submit button mode

### ISSUE THREAD

**Issue by pderiy** [KnowZero/tinymce4-languagetool#3]
Hi,

You have 2 mods.
1. Could you add next mode like 'submit_button_mode'.
It should work like on [languagetool](https://languagetool.org) page by clicking 'Check text' button.
2. Is it possible to make 1 submit button to be used in 2 tinymce editor instances?

**Comment by KnowZero** [comment]
In the next features update, I plan on adding a 'manual' mode. Which you can then call from execCommand. So as long as you add both to a button and run execCommand for both it should work in theory.

**Comment by pderiy** [comment]
Good idea, thx.

**Comment by KnowZero** [comment]
manual mode has been implemented along with mceLTProcess execCommand.
