### ISSUE TITLE
Language setting or the automatic detection

### ISSUE THREAD

**Issue by thebennos** [KnowZero/tinymce4-languagetool#6]
Hey

In lt_setLanguage
I can set the language static, but the languagetool API support a language detection. 
Why do not use it?

In every language there are new word from other languages, in german we call it "anglizismen". 
With a static set language we get a lot of trouble with these english words that are imported to other languages.

**Comment by KnowZero** [comment]
Using lt_lang you can set it to auto. I don't have it by default because it's not perfect and makes mistakes for obvious reasons.
